### PR TITLE
Move symplify/packages/easy-ci source here

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Amazing work :) go for merge when ready :+1:

**Comment by samsonasik** [comment]
It  need wait for https://github.com/symplify/symplify/pull/4538 to avoid replaced.

**Comment by samsonasik** [comment]
@TomasVotruba `${{ secrets.WORKFLOWS_TOKEN }}` token seems needed to be registered, could you add it? Thank you.

Screen Shot 2023-01-06 at 19 00 42

**Comment by TomasVotruba** [comment]
I'll add it... :+1:

**Comment by TomasVotruba** [comment]
Done :wink:

**Comment by samsonasik** [comment]
Also on `coding-standard` and `phpstan-rules`

**Comment by TomasVotruba** [comment]
Done :muscle:

**Pull request merged**
